version: '2'
services:

  # development
  dev:
    build: .
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - dev_db
      - dev_redis
    environment:
      - REDIS_HOST=dev_redis
      - REDIS_PASSWORD=BCsy8zMwZay66cim
      - DATABASE_HOST=dev_db
      - RAILS_ENV=development
    volumes:
      - $PWD:/usr/src/app
    command: bash -c "cd spec/rails_app && bundle exec rake db:create db:migrate && rails s -p3000"
  dev_db:
    image: mysql:5.6
    expose:
      - "3306"
    volumes:
      - ~/.docker-volumes/bigbluebutton_rails/dev/mysql/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=bbbrails
      - MYSQL_DATABASE=bigbluebutton_rails_dev
      - MYSQL_USER=bbbrails
      - MYSQL_PASSWORD=bbbrails
  dev_redis:
    image: redis:3.2
    expose:
      - "6379"
    command: redis-server --requirepass "BCsy8zMwZay66cim"

  # test
  test:
    image: bigbluebutton_rails-dev:latest
    build: .
    tty: true
    depends_on:
      - test_db
      - test_redis
    environment:
      - REDIS_HOST=test_redis
      - REDIS_PASSWORD=db62b65a8d19a213
      - DATABASE_HOST=test_db
      - RAILS_ENV=test
    volumes:
      - $PWD:/usr/src/app
    command: bundle exec rake rails_app:install rails_app:db spec
  test_db:
    image: mysql:5.6
    expose:
      - "3306"
    volumes:
      - ~/.docker-volumes/bigbluebutton_rails/test/mysql/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=bbbrails
      - MYSQL_DATABASE=bigbluebutton_rails_test
      - MYSQL_USER=bbbrails
      - MYSQL_PASSWORD=bbbrails
  test_redis:
    image: redis:3.2
    expose:
      - "6379"
    command: redis-server --requirepass "db62b65a8d19a213"
